# This is used to fetch Alexas top 1M websites
lists:
	wget http://s3.amazonaws.com/alexa-static/top-1m.csv.zip
	wget http://s3.amazonaws.com/data.whatheaders.com/whatheaders-latest.xml.zip
	unzip whatheaders-latest.xml.zip
	rm whatheaders-latest.xml.zip
	mv whatheaders-*xml whatheaders.xml
