from storm.twisted.transact import transact
from storm.locals import *

class Report(object):
    """
    This represents an OONI Report as stored in the database.

    report_id: this is generated by the backend and is used by the client to
               reference a previous report and append to it. It should be
               treated as a shared secret between the probe and backend.

    software_name: this indicates the name of the software performing the test
                   (this will default to ooniprobe)

    software_version: this is the version number of the software running the
                      test.

    test_name: the name of the test on which the report is being created.

    test_version: indicates the version of the test

    progress: what is the current progress of the report. This allows clients
              to report event partial reports up to a certain percentage of
              progress. Once the report is complete progress will be 100.

    content: what is the content of the report. If the current progress is less
             than 100 we should append to the YAML data structure that is
             currently stored in such field.
    """
    id = Int(primary=True)

    report_id = Unicode()

    software_name = Unicode()
    software_version = Unicode()
    test_name = Unicode()
    test_version = Unicode()
    progress = Unicode()

    content = Unicode()

