geoip:
	wget http://www.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
	gunzip GeoIPASNum.dat.gz
	wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
	gunzip GeoIP.dat.gz
	wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
	gunzip GeoLiteCity.dat.gz
clean:
	rm -f *.dat

