all: txtorcon txtraceroute txscapy

txtraceroute:
	echo "Processing dependency txtraceroute..."
	git clone https://github.com/hellais/txtraceroute.git  txtraceroute.git
	mv txtraceroute.git/txtraceroute.py txtraceroute.py
	rm -rf txtraceroute.git

txtorcon:
	echo "Processing dependency txtorcon..."
	git clone https://github.com/meejah/txtorcon.git txtorcon.git
	mv txtorcon.git/txtorcon txtorcon
	rm -rf txtorcon.git

txscapy:
	echo "Processing dependency txscapy"
	git clone https://github.com/hellais/txscapy.git txscapy.git
	mv txscapy.git/txscapy.py txscapy.py
	rm -rf txscapy.git

