# automatically syched from: ooni/pm-tools
on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          # Add to triaging board
          project-url: https://github.com/orgs/ooni/projects/47
          github-token: ${{ secrets.ADD_TO_PROJECT_GH_TOKEN }}
          labeled: bug, triage
          label-operator: OR


      - uses: actions/add-to-project@v1.0.2
        if: github.event.action == 'labeled' && startsWith(github.event.label.name, 'funder/')
        with:
          # Add to funder reporting board
          project-url: https://github.com/orgs/ooni/projects/33
          github-token: ${{ secrets.ADD_TO_PROJECT_GH_TOKEN }}
